stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
container_scanning:
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - "update gcc8"
    - "update gcc9"
    - "update gcc10"
    - "update gcc11"
    - "update gcc12"

.test-base:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - apk add python3 py3-pip
    - python3 ./tool.py test $IMAGE_DIR
  except:
    - main

.update-base:
  extends: .test-base
  script:
    - python3 ./tool.py update $IMAGE_DIR
  except: []
  only:
    - main

test gcc8:
  extends: .test-base
  variables:
    IMAGE_DIR: gcc8

update gcc8:
  extends: .update-base
  variables:
    IMAGE_DIR: gcc8

test gcc9:
  extends: .test-base
  variables:
    IMAGE_DIR: gcc9

update gcc9:
  extends: .update-base
  variables:
    IMAGE_DIR: gcc9

test gcc10:
  extends: .test-base
  variables:
    IMAGE_DIR: gcc10

update gcc10:
  extends: .update-base
  variables:
    IMAGE_DIR: gcc10

test gcc11:
  extends: .test-base
  variables:
    IMAGE_DIR: gcc11

update gcc11:
  extends: .update-base
  variables:
    IMAGE_DIR: gcc11

test gcc12:
  extends: .test-base
  variables:
    IMAGE_DIR: gcc12

update gcc12:
  extends: .update-base
  variables:
    IMAGE_DIR: gcc12
