variables:
  HUB_REPO_NAME: musicscience37/gcc-ci

.build-base:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$IMAGE_NAME" "$BUILD_CONTEXT"
    - sh run_test.sh "$BUILD_CONTEXT"
    - docker push "$IMAGE_NAME"
  artifacts:
    paths:
      - test/build_$BUILD_CONTEXT
    when: always
    expire_in: "30 days"

.build-hub-base:
  extends: .build-base
  after_script:
    - docker login -u "$HUB_USER_NAME" -p "$HUB_ACCESS_TOKEN"
    - docker tag "$IMAGE_NAME" "$HUB_IMAGE_NAME"
    - docker push "$HUB_IMAGE_NAME"

build gcc8:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc8
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build gcc8 tag:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc8
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT-$CI_COMMIT_TAG"
  only:
    - tags

build gcc8 master:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc8
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT"
  only:
    - master

build gcc9:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc9
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build gcc9 tag:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc9
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT-$CI_COMMIT_TAG"
  only:
    - tags

build gcc9 master:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc9
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT"
  only:
    - master

build gcc10:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc10
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build gcc10 tag:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc10
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT-$CI_COMMIT_TAG"
  only:
    - tags

build gcc10 master:
  extends: .build-hub-base
  variables:
    BUILD_CONTEXT: gcc10
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$BUILD_CONTEXT"
  only:
    - master
