.build-base:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$IMAGE_NAME" "$BUILD_CONTEXT"
    - sh run_test.sh "$BUILD_CONTEXT"
    - docker push "$IMAGE_NAME"
  artifacts:
    paths:
      - test/build_$BUILD_CONTEXT
    when: always
    expire_in: '30 days'

build gcc8:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc8
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master

build gcc8 master:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc8
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
  only:
    - master

build gcc9:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc9
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master

build gcc9 master:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc9
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
  only:
    - master

build gcc10:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc10
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT-$CI_COMMIT_REF_SLUG"
  except:
    - master

build gcc10 master:
  extends: .build-base
  variables:
    BUILD_CONTEXT: gcc10
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$BUILD_CONTEXT"
  only:
    - master
